vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            uri_prefix: /images/products
            upload_destination: '%upload_directory%/upload/ressources'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 
